/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeButton: typeof import('./src/components/AddNodeButton.vue')['default']
    AddTriggerButton: typeof import('./src/components/AddTriggerButton.vue')['default']
    BuildDetailsModal: typeof import('./src/components/BuildDetailsModal.vue')['default']
    BuildHistoryDialog: typeof import('./src/components/BuildHistoryDialog.vue')['default']
    BuildHistoryItem: typeof import('./src/components/BuildHistoryItem.vue')['default']
    BuildHistoryList: typeof import('./src/components/BuildHistoryList.vue')['default']
    BuildHistoryView: typeof import('./src/components/BuildHistoryView.vue')['default']
    BuildStatusBadge: typeof import('./src/components/BuildStatusBadge.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DevBenefitsOverride: typeof import('./src/components/DevBenefitsOverride.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DisconnectedPage: typeof import('./src/components/DisconnectedPage.vue')['default']
    EditorNodeAction: typeof import('./src/components/nodes/EditorNodeAction.vue')['default']
    EditorNodeCondition: typeof import('./src/components/nodes/EditorNodeCondition.vue')['default']
    EditorNodeDummy: typeof import('./src/components/nodes/EditorNodeDummy.vue')['default']
    EditorNodeEvent: typeof import('./src/components/nodes/EditorNodeEvent.vue')['default']
    EditorNodeEventEmpty: typeof import('./src/components/nodes/EditorNodeEventEmpty.vue')['default']
    EditorNodeLoop: typeof import('./src/components/nodes/EditorNodeLoop.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    ParamEditor: typeof import('./src/components/nodes/ParamEditor.vue')['default']
    ParamEditorBody: typeof import('./src/components/nodes/ParamEditorBody.vue')['default']
    PluginIcon: typeof import('./src/components/nodes/PluginIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioListItem: typeof import('./src/components/ScenarioListItem.vue')['default']
    ScenarioListItemFile: typeof import('./src/components/ScenarioListItemFile.vue')['default']
    ScenarioListItemRecent: typeof import('./src/components/ScenarioListItemRecent.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubscriptionLoadingIndicator: typeof import('./src/components/SubscriptionLoadingIndicator.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UpgradeDialog: typeof import('./src/components/UpgradeDialog.vue')['default']
    UpgradeNowButton: typeof import('./src/components/UpgradeNowButton.vue')['default']
    WebFilePicker: typeof import('./src/components/WebFilePicker.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
