export const defaultElectronConfig = {
  alwaysOnTop: false,
  appBundleId: 'com.pipelab.app',
  appCategoryType: '',
  appCopyright: 'Copyright © 2024 Pipelab',
  appVersion: '1.0.0',
  author: 'Pipelab',
  customMainCode: '',
  description: 'A simple Electron application',
  electronVersion: '',
  disableAsarPackaging: true,
  forceHighPerformanceGpu: false,
  enableExtraLogging: false,
  clearServiceWorkerOnBoot: false,
  enableDisableRendererBackgrounding: false,
  enableInProcessGPU: false,
  frame: true,
  fullscreen: false,
  icon: '',
  height: 600,
  name: 'Pipelab',
  toolbar: true,
  transparent: false,
  width: 800,
  enableSteamSupport: false,
  steamGameId: 480,
  enableDiscordSupport: false,
  discordAppId: '',
  ignore: [],
  openDevtoolsOnStart: false,
} satisfies DesktopApp.Electron
