<template>
  <Layout>
    <WorkflowShell
      :flow-id="flowId"
      :project-id="projectId"
      :title="workflowTitle"
      subtitle="Artifacts across workflow runs"
      active="artifacts"
    >
      <main class="artifacts-page">
        <header class="list-heading">
          <div>
            <h2>Artifacts</h2>
            <p>Discover files generated by this workflow’s runs.</p>
          </div>
          <span v-if="!loading && !loadError" class="artifact-count">
            {{ artifacts.length }} {{ artifacts.length === 1 ? "artifact" : "artifacts" }}
          </span>
        </header>

        <Message v-if="loadError" severity="error" :closable="false" role="alert">
          <div class="state-copy">
            <strong>Couldn’t load artifacts</strong>
            <span>{{ loadError }}</span>
            <Button label="Retry" text size="small" @click="loadArtifacts" />
          </div>
        </Message>
        <Message v-if="actionError" severity="error" :closable="false" role="alert">
          {{ actionError }}
        </Message>

        <div
          v-if="loading && !artifacts.length"
          class="artifact-skeleton"
          aria-busy="true"
          aria-label="Loading artifacts"
        >
          <div v-for="n in 4" :key="n" class="skeleton-row"><span /><span /><span /></div>
        </div>
        <div
          v-else-if="!loading && !loadError && !artifacts.length"
          class="empty-state"
          role="status"
        >
          <i class="mdi mdi-package-variant-closed" aria-hidden="true" />
          <strong>No artifacts yet</strong>
          <span>Artifacts generated by this workflow will appear here.</span>
          <Button label="View runs" icon="pi pi-arrow-right" text @click="viewRuns" />
        </div>
        <ul v-else-if="!loadError" class="artifact-list" aria-label="Workflow artifacts">
          <li v-for="artifact in artifacts" :key="artifact.id" class="artifact-row">
            <div class="artifact-main">
              <i class="mdi mdi-package-variant artifact-icon" aria-hidden="true" />
              <div class="artifact-content">
                <strong class="artifact-name">{{ artifact.displayName }}</strong>
                <div class="artifact-metadata" aria-label="Artifact details">
                  <span v-if="artifact.releaseVersion">Release {{ artifact.releaseVersion }}</span>
                  <span v-if="artifact.platform">Platform: {{ artifact.platform }}</span>
                  <span v-if="artifact.architecture"
                    >Architecture: {{ artifact.architecture }}</span
                  >
                  <span v-if="artifact.format">Format: {{ artifact.format }}</span>
                  <span v-if="artifact.kind">Kind: {{ artifact.kind }}</span>
                  <span v-if="artifact.size !== undefined">{{ formatSize(artifact.size) }}</span>
                </div>
                <div class="artifact-provenance">
                  <span>{{ formatDate(artifact.runDate) }}</span>
                  <span aria-hidden="true">·</span>
                  <span>{{ artifact.runLabel }} · #{{ shortId(artifact.runId) }}</span>
                  <Tag v-if="artifact.localPath" value="Local" severity="secondary" />
                  <Tag v-if="artifact.hostedArtifactId" value="Cloud" severity="info" />
                  <span v-if="!artifact.localPath && !artifact.hostedArtifactId">Unavailable</span>
                </div>
              </div>
            </div>
            <div class="artifact-actions">
              <Button
                v-if="artifact.localPath"
                label="Open"
                icon="mdi mdi-folder-open-outline"
                text
                size="small"
                :aria-label="`Open ${artifact.displayName}`"
                @click="openArtifact(artifact.localPath)"
              />
              <Button
                v-if="artifact.hostedArtifactId"
                label="Download"
                icon="mdi mdi-download"
                text
                size="small"
                :aria-label="`Download ${artifact.displayName}`"
                @click="downloadArtifact(artifact.hostedArtifactId)"
              />
              <Button
                label="View run"
                icon="mdi mdi-open-in-new"
                text
                size="small"
                :aria-label="`View run ${shortId(artifact.runId)} for ${artifact.displayName}`"
                @click="viewRun(artifact.runId)"
              />
            </div>
          </li>
        </ul>
      </main>
    </WorkflowShell>
  </Layout>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import Layout from "@renderer/components/Layout.vue";
import WorkflowShell from "@renderer/components/WorkflowShell.vue";
import Button from "primevue/button";
import Message from "primevue/message";
import Tag from "primevue/tag";
import { useAPI } from "@renderer/composables/api";
import { aggregateWorkflowArtifacts } from "./workflow-artifacts-state";

const route = useRoute();
const router = useRouter();
const api = useAPI();
const flowId = computed(() => String(route.params.flowId || ""));
const projectId = computed(() => String(route.params.projectId || ""));
const basePath = computed(() => `/workflows/${flowId.value}/${projectId.value}`);
const artifacts = ref<ReturnType<typeof aggregateWorkflowArtifacts>>([]);
const loading = ref(true);
const loadError = ref("");
const actionError = ref("");
const workflowName = ref("");
const workflowTitle = computed(
  () => workflowName.value || artifacts.value[0]?.workflowName || "Workflow",
);
let loadGeneration = 0;

const loadArtifacts = async () => {
  const generation = ++loadGeneration;
  const workflowId = flowId.value;
  const pipelineId = projectId.value;
  const isCurrentRequest = () =>
    generation === loadGeneration && flowId.value === workflowId && projectId.value === pipelineId;

  if (!artifacts.value.length) loading.value = true;
  loadError.value = "";
  actionError.value = "";
  void api
    .execute("workflow:load", { workflowId, projectId: pipelineId })
    .then((response) => {
      if (
        isCurrentRequest() &&
        response.type === "success" &&
        response.result.id === workflowId &&
        response.result.project === pipelineId
      )
        workflowName.value = response.result.name;
    })
    .catch(() => {});
  try {
    const response = await api.execute("build-history:get-all", {
      query: { workflowId, pipelineId },
    });
    if (!isCurrentRequest()) return;
    if (response.type === "error") throw new Error(response.ipcError);
    artifacts.value = aggregateWorkflowArtifacts(response.result.entries, workflowId, pipelineId);
  } catch (cause) {
    if (isCurrentRequest())
      loadError.value = cause instanceof Error ? cause.message : String(cause);
  } finally {
    if (isCurrentRequest()) loading.value = false;
  }
};

const formatDate = (timestamp: number) =>
  new Date(timestamp).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
const formatSize = (bytes: number) => {
  if (!Number.isFinite(bytes) || bytes < 0) return "—";
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB", "TB"];
  let size = bytes / 1024;
  let unit = 0;
  while (size >= 1024 && unit < units.length - 1) {
    size /= 1024;
    unit++;
  }
  return `${size.toFixed(size >= 10 ? 0 : 1)} ${units[unit]}`;
};
const shortId = (id: string) => (id.length > 12 ? id.slice(0, 8) : id);
const viewRuns = () => router.push(`${basePath.value}/runs`);
const viewRun = (runId: string) => router.push(`${basePath.value}/runs/${runId}`);

const openArtifact = async (path: string) => {
  try {
    const response = await api.execute("shell:openPath", { path });
    if (response.type === "error") actionError.value = response.ipcError;
  } catch (cause) {
    actionError.value = cause instanceof Error ? cause.message : String(cause);
  }
};

const downloadArtifact = async (hostedArtifactId: string) => {
  try {
    const response = await api.execute("pipelab-cloud:artifact-download-url", { hostedArtifactId });
    if (response.type === "error") {
      actionError.value = response.ipcError;
      return;
    }
    const link = document.createElement("a");
    link.href = response.result.url;
    link.target = "_blank";
    link.rel = "noopener noreferrer";
    link.click();
  } catch (cause) {
    actionError.value = cause instanceof Error ? cause.message : String(cause);
  }
};

watch([flowId, projectId], () => {
  artifacts.value = [];
  workflowName.value = "";
  void loadArtifacts();
});
onMounted(loadArtifacts);
onUnmounted(() => {
  loadGeneration++;
});
</script>

<style scoped>
.artifacts-page {
  color: var(--text-color);
}
.list-heading {
  display: flex;
  align-items: end;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 14px;
}
.list-heading h2 {
  margin: 0;
  font-size: 1.15rem;
}
.list-heading p {
  margin: 4px 0 0;
  color: var(--p-text-muted-color, var(--text-color-secondary));
  font-size: 0.875rem;
}
.artifact-count {
  color: var(--p-text-muted-color, var(--text-color-secondary));
  font-size: 0.8rem;
}
.state-copy {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px 12px;
}
.state-copy span {
  flex-basis: 100%;
}
.artifact-list {
  display: grid;
  gap: 8px;
  margin: 0;
  padding: 0;
  list-style: none;
}
.artifact-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  min-width: 0;
  padding: 14px 16px;
  border: 1px solid var(--p-surface-200, var(--surface-border));
  border-radius: 8px;
  background: var(--p-surface-0, var(--surface-card));
}
.artifact-main {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  min-width: 0;
}
.artifact-icon {
  flex: 0 0 auto;
  margin-top: 2px;
  color: var(--p-text-muted-color, var(--text-color-secondary));
  font-size: 1.15rem;
}
.artifact-content {
  display: grid;
  gap: 7px;
  min-width: 0;
}
.artifact-name {
  overflow-wrap: anywhere;
}
.artifact-metadata,
.artifact-provenance {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px 10px;
  color: var(--p-text-muted-color, var(--text-color-secondary));
  font-size: 0.78rem;
}
.artifact-provenance :deep(.p-tag) {
  font-size: 0.68rem;
}
.artifact-actions {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  flex: 0 0 auto;
  flex-wrap: wrap;
  gap: 2px;
}
.artifact-skeleton {
  display: grid;
  gap: 8px;
}
.skeleton-row {
  display: grid;
  grid-template-columns: minmax(120px, 1fr) 160px 96px;
  align-items: center;
  gap: 16px;
  height: 66px;
  padding: 12px 16px;
  border: 1px solid var(--p-surface-200, var(--surface-border));
  border-radius: 8px;
}
.skeleton-row span {
  height: 10px;
  border-radius: 4px;
  background: var(--p-surface-100, var(--surface-ground));
}
.skeleton-row span:first-child {
  max-width: 320px;
}
.empty-state {
  display: grid;
  justify-items: center;
  gap: 8px;
  padding: 48px 16px;
  color: var(--p-text-muted-color, var(--text-color-secondary));
  text-align: center;
}
.empty-state > i {
  font-size: 1.75rem;
}
.empty-state strong {
  color: var(--text-color);
}
:root.dark .artifact-row {
  border-color: var(--p-surface-700, #3f3f46);
  background: var(--p-surface-900, #18181b);
}
:root.dark .skeleton-row {
  border-color: var(--p-surface-700, #3f3f46);
}
:root.dark .skeleton-row span {
  background: var(--p-surface-800, #27272a);
}
@media (max-width: 720px) {
  .artifact-row {
    align-items: flex-start;
    flex-direction: column;
  }
  .artifact-actions {
    width: 100%;
    justify-content: flex-start;
    margin-left: 28px;
  }
}
@media (max-width: 420px) {
  .list-heading {
    align-items: flex-start;
    flex-direction: column;
  }
  .artifact-row {
    padding: 12px;
  }
  .artifact-actions {
    margin-left: 0;
  }
}
</style>
