/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeButton: typeof import('./src/components/AddNodeButton.vue')['default']
    Boolean: typeof import('./src/components/controls/boolean/boolean.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('./src/components/controls/checkbox/checkbox.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EditorNodeAction: typeof import('./src/components/nodes/EditorNodeAction.vue')['default']
    EditorNodeCondition: typeof import('./src/components/nodes/EditorNodeCondition.vue')['default']
    EditorNodeDummy: typeof import('./src/components/nodes/EditorNodeDummy.vue')['default']
    EditorNodeEvent: typeof import('./src/components/nodes/EditorNodeEvent.vue')['default']
    EditorNodeLoop: typeof import('./src/components/nodes/EditorNodeLoop.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Inplace: typeof import('primevue/inplace')['default']
    Input: typeof import('./src/components/controls/input/input.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Panel: typeof import('primevue/panel')['default']
    ParamEditor: typeof import('./src/components/nodes/ParamEditor.vue')['default']
    'ParamEditor.old': typeof import('./src/components/nodes/ParamEditor.old.vue')['default']
    Path: typeof import('./src/components/controls/path/path.vue')['default']
    PluginIcon: typeof import('./src/components/nodes/PluginIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioListItem: typeof import('./src/components/ScenarioListItem.vue')['default']
    ScenarioListItemFile: typeof import('./src/components/ScenarioListItemFile.vue')['default']
    ScenarioListItemRecent: typeof import('./src/components/ScenarioListItemRecent.vue')['default']
    Select: typeof import('./src/components/controls/select/select.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
}
