name: Electron Forge CI/CD

on:
  push:
    tags:
      - '**'
    branches:
      - '**'
  # pull_request:
  #   branches: [main]
  # merge_group:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js 22.5.1
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: 'pnpm'

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pnpm install

      - name: Build app deps
        run: pnpm turbo run build --filter=@pipelab/app^...

      - name: Package application
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: cd apps/desktop && pnpm electron-forge publish --dry-run

      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: cd apps/desktop && pnpm test:e2e:raw

      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-playwright
          path: apps/desktop/playwright/**/*

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-out
          path: apps/desktop/out/**/*

  release:
    permissions:
      contents: write
      discussions: write
    needs: build-and-test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-out
          path: apps/desktop/out

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js 22.5.1
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prod=false

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd apps/desktop && pnpm electron-forge publish --from-dry-run
